services:
  # subscription-service:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     NODE_ENV: production
  #     DATABASE_URL: ${DATABASE_URL}
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network
  subscription_service_db:
    image: postgres:15-alpine
    ports:
      - '5434:5432'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscription_service
    volumes:
      - subscription-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  subscription-data:
    driver: local

networks:
  app-network:
    driver: bridge
